%%{init: {"flowchart": {"curve": "linear"}}}%%
graph TD;
	__start__([__start__]):::startNode
	preparegraphstate[prepare graph state]
	initializesandbox[initialize sandbox]
	generateplancontextaction[generate plan context action]
	takeplanactions[take plan actions]
	generateplan[generate plan]
	notetaker[notetaker]
	interruptproposedplan[interrupt proposed plan]
	determineneedscontext[determine needs context]
	diagnoseerror[diagnose error]
	__end__([__end__]):::endNode

	__start__ --> preparegraphstate
	diagnoseerror --> generateplancontextaction
	generateplan --> notetaker
	initializesandbox --> generateplancontextaction
	notetaker --> interruptproposedplan

	generateplancontextaction -.-> takeplanactions
	generateplancontextaction -.-> generateplan
	preparegraphstate -.-> __end__
	preparegraphstate -.-> initializesandbox
	takeplanactions -.-> generateplancontextaction
	takeplanactions -.-> diagnoseerror
	takeplanactions -.-> generateplan
	interruptproposedplan -.-> __end__
	interruptproposedplan -.-> determineneedscontext
	determineneedscontext -.-> generateplancontextaction
	determineneedscontext -.-> generateplan

	classDef startNode fill:#90EE90,stroke:#333,stroke-width:2px;
	classDef endNode fill:#FFB6C1,stroke:#333,stroke-width:2px;
